### ISSUE TITLE
defect tracking 440

### ISSUE THREAD

**Issue by sarkhadka7** [sarkhadka7/Defect-tracking-480#1]
* Start Bee Flogger
* Create an unnamed document simply containing the letter “a”
* Click on the FTP button on the toolbar
* Try to ftp to your server

BUG: Observe; the ftp server is no longer responding. Indeed ps -augx shows that it is not even running and there is a core dump in /.

EXPECTED: No crash

**Comment by Yozi47** [comment]
Not our code, Jill, that’s just proftpd which comes with Linux.

**Comment by sarkhadka7** [comment]
That doesn’t sound right. I’ve never been able to crash proftpd when I connect with a normal ftp client. Our code crashes it every single time. Ftp servers don’t just “crash”.

**Comment by Yozi47** [comment]
Mikey, can you look at this? Maybe your client code is doing something wrong.

**Comment by rukuri0** [comment]
I think I was passing the user name instead of the password or something…

**Comment by rukuri0** [comment]
Whoa. That’s strange. Lemme debug this.

**Comment by rukuri0** [comment]
I’m thinking it might be MikeyStrCpy()…

**Comment by rukuri0** [comment]
Ahhh!
FIXED!
